### ISSUE TITLE
[Feature request] "Free Trial" or "Max Level" filter

### ISSUE THREAD

**Issue by JodanJodan** [Haselnussbomber/LeveHelper#15]
For free trial users, it would be useful to be able to filter out all leves of level ≥ 70, filtering either by max level or a 'Free Trial?' boolean field.

**Comment by Haselnussbomber** [comment]
I totally forgot about this, sorry!
I've added min and max level filter in [v2.4.0](https://github.com/Haselnussbomber/LeveHelper/releases/tag/v2.4.0).
