### ISSUE TITLE
[Bug] Incomplete list problem

### ISSUE THREAD

**Issue by github-1348A55** [Haselnussbomber/LeveHelper#2]
The display area of the incomplete list has been reduced.
This happens when you receive multiple orders of a Leve at the same place and  want to show only that area, or only the corresponding Levemete.
If there is only one "Accepted" there is no problem, but if there are two or more, it will occur.

I couldn't see this issue in other settings or tabs.

**Comment by Haselnussbomber** [comment]
Hmm, I'm not really sure what you mean.

As you can see here, I just accepted 3 Carpenter leves from Tierney and have the Incomplete filter active. (Sorry, my game is in German^^)

![ffxiv_dx11_2023-04-23_17-31-07](https://user-images.githubusercontent.com/96642047/233849069-9ee07401-4ded-4f29-9bb9-e3b6293fed9f.png)

If I now click the "Set Current Zone" button, it sets it to "Tiefer Wald" (Central Shroud, this is where I am). It correctly filters out the leve for Gridania (which is probably the location of the levemete). You can see it grouped by zone in the quest log. This is how the game does it, not LeveHelpers doing.

![ffxiv_dx11_2023-04-23_17-32-19](https://user-images.githubusercontent.com/96642047/233849160-f8a1f7f5-2514-468b-8b3c-32919004f4de.png)

If I misunderstood you, please explain again. 😅

**Comment by github-1348A55** [comment]
Thanks for your reply.
It may happen in a specific language.
I'm playing games on Japanese settings and display.

There is no display problem in the initial state without any scrolling.
![p1](https://user-images.githubusercontent.com/104717050/233852563-73147968-192c-4d37-ad40-e521a05c5d48.png)

Screen that scrolls down the list a bit, at which point the bottom half of the Incomplete list is gone.
![p2](https://user-images.githubusercontent.com/104717050/233852571-ca32fa68-9b8b-45ad-a151-91666ad809e3.png)

Screen at the bottom of the list, which is also not normal.
![p3](https://user-images.githubusercontent.com/104717050/233852576-b174b93c-c49a-40d1-b8a8-9e57f1c473d5.png)

For more information on this screenshot.
Location: Ishgard
Levemete: Fionnuala
Accepted Leves: Culinarians

Sorry for the poor explanation...

**Comment by Haselnussbomber** [comment]
Ohh, I see now!

Yes, it makes sense. The ImGuiListClipper expects each row to be the same height, which obviously is not the case when items are displayed for accepted levequests. This results in a wrong calculation of the rows that should be displayed.

I've removed it from the plugin, so it renders the whole list (less efficient, but not too bad) and released it as [v2.0.1](https://github.com/Haselnussbomber/LeveHelper/releases/tag/v2.0.1).
It should work correctly now. 🙂

**Comment by Haselnussbomber** [comment]
Also your explanation was just fine with the screenshots. I was just having dinner in the meantime. :rofl:

**Comment by github-1348A55** [comment]
Thanks for the update!
It was the middle of the night when I posted before, so I went straight to sleep. 😴
I just checked and the display of the incomplete list was no problem.

Maybe you're asleep right now.
Good night and then good morning Haselnussbomber!
