### ISSUE TITLE
Levequest IDs

### ISSUE THREAD

**Issue by Pyresque** [Haselnussbomber/LeveHelper#3]
Love the new updates, however I miss having the leve quest IDs listed in the interface as it was very convenient to me personally. Is there any way we could have those back, even if just as option to toggle? Would appreciate it a lot. :) 

Great plugin and has been a huge help in achievement hunting, thanks so much for your work!

**Comment by Haselnussbomber** [comment]
Hey,
the id column is still in the plugin! Maybe you have hidden it by accident?
Right click the columns of the table, it should give you the option to enable it again! 😃
![ffxiv_dx11_2023-05-03_10-31-32](https://user-images.githubusercontent.com/96642047/235867422-4e7ac3c4-b5fc-4fd5-a72e-1716aedea595.png)

**Comment by Pyresque** [comment]
Oh my god LOL I must have hidden it, I hadn't tried clicking it yet LMAO Now it's showing up again, thank you so much!
