### ISSUE TITLE
Iron ore is organized under "Other" when it can be gathered

### ISSUE THREAD

**Issue by benphantom41** [Haselnussbomber/LeveHelper#6]
When looking at the "Queue" tab, Iron Ore is organized under the "Other" label when it can be normally gathered like most other ore. 

![IronOre](https://github.com/Haselnussbomber/LeveHelper/assets/48699776/444487b5-12c8-4d28-956f-f173f774458b)

I figured this was an oversight

**Comment by Haselnussbomber** [comment]
Thanks for reporting this! Fixed with [v2.0.6](https://github.com/Haselnussbomber/LeveHelper/releases/tag/v2.0.6). 😄👍
