### ISSUE TITLE
Hidden Items that can be gathered are sorted under "Other"

### ISSUE THREAD

**Issue by benphantom41** [Haselnussbomber/LeveHelper#7]
Hidden Items that can be gathered are sorted under the "Other" category while in the "Queue" Tab

- Mythrite Ore
- Titanium Ore
- Birch Logs

![image](https://github.com/Haselnussbomber/LeveHelper/assets/48699776/4c713e94-e3f2-42ab-98b3-3a04c7f3b0e0)

**Comment by Haselnussbomber** [comment]
I've released [v2.0.7](https://github.com/Haselnussbomber/LeveHelper/releases/tag/v2.0.7), which should fix it.
The plugin now scans every gathering point for items. Previously, I filtered out gathering nodes which have a territory id of 1, meaning they are not associated with a specific zone.
I hope the game data doesn't have some surprises for us. If you find any, please let me know. 🙂
