### ISSUE TITLE
[Question] Show required materials.

### ISSUE THREAD

**Issue by github-1348A55** [Haselnussbomber/LeveHelper#9]
![leve-queue](https://github.com/Haselnussbomber/LeveHelper/assets/104717050/3df30407-b306-4163-90c2-eb9fe7f1124d) ![leve-recipe](https://github.com/Haselnussbomber/LeveHelper/assets/104717050/5330c06d-145e-44e4-b689-ba22ef609881)

I tried Leve for the first time in a while.
LeveHelper did not display any of the required materials.
Previously, the name and number of materials required for crafting requested items were listed.

I don't know the cause.
Is there a good way for players to cope?

**Comment by Haselnussbomber** [comment]
Hey, thanks for reporting the issue!

I made a mistake with the last update, but I just fixed it and released [v2.1.1](https://github.com/Haselnussbomber/LeveHelper/releases/tag/v2.1.1). Please update!

Sorry about this!

(For the technical reason: It was a bug in detecting if an item has recipes. The logic was flipped ([commit of the fix](https://github.com/Haselnussbomber/HaselCommon/commit/ff8d14da0d8f9f2482aa9d358c012f1efdd1e25b)))
